# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-31 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamoving', '0002_auto_20190530_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulation',
            name='use_csr',
            field=models.SmallIntegerField(choices=[('1', '启用临时表'), ('0', '不使用临时表')], default='1', verbose_name='是否使用临时表'),
        ),
    ]
