# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-11 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamoving', '0004_auto_20190603_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
