# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-25 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamoving', '0006_task_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='path',
            field=models.CharField(default='', max_length=100, verbose_name='路径'),
        ),
    ]
