# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='权限名称')),
                ('describe', models.TextField(verbose_name='权限描述')),
                ('key', models.CharField(max_length=64, verbose_name='key')),
                ('group_set', models.ManyToManyField(to='auth.Group', verbose_name='用户组')),
            ],
        ),
    ]
