# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-25 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruleManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='right',
            table='',
        ),
    ]
