# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='配置项名称')),
                ('alias', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='配置项唯一标识')),
                ('is_mod', models.BooleanField(default=False, verbose_name='是否模板')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.Config')),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='ConfigType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='类型名称')),
                ('alias', models.CharField(default='', max_length=30, verbose_name='类型唯一标识')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_type', to='config.ConfigType')),
            ],
            options={
                'db_table': 'config_type',
            },
        ),
        migrations.CreateModel(
            name='SubConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300, verbose_name='键')),
                ('value', models.CharField(max_length=300, verbose_name='值')),
                ('alias', models.CharField(default='', max_length=30, verbose_name='子配置项名称')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Config')),
            ],
            options={
                'db_table': 'subconfig',
            },
        ),
        migrations.AddField(
            model_name='config',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.ConfigType'),
        ),
    ]
