# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-11 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configtype',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='subconfig',
            name='config',
        ),
        migrations.RemoveField(
            model_name='config',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='config',
            name='is_mod',
        ),
        migrations.RemoveField(
            model_name='config',
            name='name',
        ),
        migrations.RemoveField(
            model_name='config',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='config',
            name='type',
        ),
        migrations.AddField(
            model_name='config',
            name='info',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='配置名称'),
        ),
        migrations.AddField(
            model_name='config',
            name='key',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='键'),
        ),
        migrations.AddField(
            model_name='config',
            name='value',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='值'),
        ),
        migrations.DeleteModel(
            name='ConfigType',
        ),
        migrations.DeleteModel(
            name='SubConfig',
        ),
    ]
