# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-11 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20190611_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='config_type',
            field=models.CharField(default='', max_length=50, verbose_name='配置类型'),
        ),
    ]
