# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-11 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_config_config_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='config_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='配置类型'),
        ),
    ]
