# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-06 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='typer',
            field=models.SmallIntegerField(choices=[(0, 'ORACLE')], default=0, verbose_name='应用类型'),
        ),
    ]
