# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-11 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_auto_20190606_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='apps',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
