# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='功能名称')),
                ('description', models.TextField(max_length=200, verbose_name='功能描述')),
                ('codename', models.CharField(max_length=50, null=True, verbose_name='功能代码')),
                ('url', models.TextField(max_length=200, null=True, verbose_name='功能链接')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'function',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('description', models.TextField(max_length=200, verbose_name='模块描述')),
                ('codename', models.CharField(max_length=50, null=True, verbose_name='模块代码')),
                ('url', models.TextField(max_length=200, null=True, verbose_name='模块链接')),
                ('icon', models.CharField(max_length=50, null=True, verbose_name='模块图标')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.AddField(
            model_name='function',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_function', to='authority.Module'),
        ),
    ]
